name: jenkins_p2g_docs
channels:
  - conda-forge
dependencies:
  - behave
  - graphviz
  - pip
  - sphinx>=8.2.2
  - pytest
  - matplotlib
  - pip:
    - pytest-lazy-fixtures
    - graphviz
#    - sphinx-argparse
    - git+https://github.com/djhoese/sphinx-argparse.git@bugfix-section-nums
