name: jenkins_p2g_docs
channels:
  - conda-forge
dependencies:
  - behave
  - graphviz
  - pip
  - sphinx
  - pytest
  - pytest-lazy-fixture
  - matplotlib
  - pip:
    - graphviz
    - sphinx-argparse
    - sphinxcontrib-apidoc
